### PR TITLE
Use state controlled industry job losses

### PR DESCRIPTION
**Pull request by ajjitn**
NOTE: Total employment numbers differ when we use the weighted NY-WA job loss file (12.3 million) vs the state controlled job loss file (12.9 million). Need to think through carefully if this makes sense.

### CODE REVIEW

**Comment by grahamimac** [comment]
Hmm... Yes they should be different and yes state controls should be higher than WA + NY. The direction is right but seems slightly higher than I would have expected. WA + NY job loss is 13.1%, while state control totals show 13.4%, which is a ~2% difference. 12.9/12.4 is a ~4% difference. Small discrepancy likely could be accounted for by interaction with industries within states (e.g., states that were inflated with control totals tended to have more people working in industries with job losses in WA/NY). Would like @cdavisurban to weigh in/take a quick look too.

**Comment by ajjitn** [comment]
As stated in slack, 12.3 was a typo, its actually 12.6 million jobs lost using the WA/NY weighted average.  And 12.9/12.6 is about a 2% difference so looks like it adds up

**Comment by ajjitn** [comment]
@cdavisurban have you had a chance to give this a quick look? I want to merge to staging and go through a dry run later today

**Comment by grahamimac** [comment]
If Chris doesn't have time I'm fine moving ahead with a merge as we've both reviewed the others' work at this point.

**Comment by cdavisurban** [comment]
Just started reviewing! Hope to be finished by 1.

**Comment by grahamimac** [comment]
Thanks Chris. Ajjit, I think we need to explicitly add the manual steps to the README, but don't want to do it right now as we're about to merge. Something like:

"Because the New York State data and BLS state-level advanced claims are released in PDF format, we use a manual process to update those files, as follows:

1. Download the most recent BLS state-level advanced claims data from https://oui.doleta.gov/unemploy/claims.asp. Replace past weeks of `data/raw-data/small/initial-claims-bls-state.xlsx` with this data.

2. Convert the most recent PDF to excel from https://www.dol.gov/ui/data.pdf, and add the current week of data to the sheet in `data/raw-data/small/initial-claims-bls-state.xlsx`. Be sure that states line up - they are in different orders in the PDF and the claims data spreadsheet. 

3. Download the most recent NY state data from https://labor.ny.gov/stats/weekly-ui-claims-report.shtm. Convert from PDF to excel and add the current week of data to the sheet in `data/raw-data/small/ny-manual-input-data.xlsx`."

Or something like that.

**Pull request merged**
